[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
# Forces 4MB flash configuration
board_build.flash_mode = dio
board_upload.flash_size = 4MB
monitor_filters = esp32_exception_decoder, direct